### ISSUE TITLE
Cannot build backend app through parcel after upgrading f36 components to version 4

### ISSUE THREAD

**Issue by AbuHafsa** [contentful/apps#1724]
**Describe the bug**

I have created an app using `default-values-backend` and decided to upgrade f36 packages as it is using an older version. once I run `start` it ends unexpectedly with an error.

**To Reproduce**
- `npx create-contentful-app  --example default-values-backend`
- Configure a sample app from your account and provide public key. 
- `npm install @contentful/f36-components @contentful/browserslist-config`
- Replace imports in `public/config.js` with `@contentful/f36-components` and replace some elements like `TextField` to `TextInput`
- `npm run start`

**Expected behavior**

It builds the frontend and runs the server. 

**Screenshots**
```
> backend-app@1.0.0 buildFrontend
> parcel build public/index.html

🚨  .../backend-app/node_modules/@contentful/f36-button/dist/esm/index.js: Unexpected token: operator (?)
    at Z.get (.../backend-app/node_modules/terser/dist/bundle.min.js:1:525)
    at Object.errorToJson (.../backend-app/node_modules/@parcel/utils/src/errorUtils.js:9:20)
    at Pipeline.process (.../backend-app/node_modules/parcel-bundler/src/Pipeline.js:29:26)
    at async Object.run (.../backend-app/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Bundler.loadAsset (.../backend-app/node_modules/parcel-bundler/src/Bundler.js:577:19)
    at async .../backend-app/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 7)
    at async Bundler.loadAsset (.../backend-app/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async .../backend-app/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 4)

Process finished with exit code 1
```

**Desktop (please complete the following information):**
 - OS: macOS @ 12.5.1
 - Browser: Chrome @  105.0.5195.102

**Additional context**

Interestingly when I have added another script that runs `parcel watch public/index.html` and ran the server separately using `ts-node` with a few changes on the code, this have rendered the configuration page without any errors.

**Comment by AbuHafsa** [comment]
Upon further investigation, I realised that the app uses `parcel-bundler` which is an old version of `parcel`. I am about to submit a PR to fix this issue.
